[package]
name = "rbdc-oracle"
version = "0.1.0"
edition = "2021"
description = "a simple oracle driver for rbatis"
readme = "Readme.md"
authors = ["ce <chenpengfan1996@gmail.com>"]
license = "Apache-2.0"

[dependencies]
rbs = "0.1"
rbdc = { version = "0.1", default-features = false }
oracle = { version="0.5", features = ["chrono"]}
serde = "1"
serde_json = "1"
futures-io = {version="0.3.21",features=["std"]}
futures-core = { version = "0.3.19", default-features = false }
futures-util = {version="0.3.21",features = ["alloc", "sink"]}
chrono = "0.4.19"
rust_decimal = "1.25.0"
log="0.4"
bigdecimal = { version = "0.2.0", features = ["serde"] }

[dev-dependencies]
tokio = {version="1",features = ["full"]}
