[package]
name = "rbdc-oracle"
version = "0.3.1"
edition = "2021"
description = "a simple oracle driver for rbatis"
readme = "Readme.md"
authors = ["chenpengfan<chenpengfan1996@gmail.com>"]
license = "Apache-2.0"

[dependencies]
rbs = "4.3.2"
rbdc = "4.3.2"
oracle = { version="0.5", features = ["chrono"]}
serde = "1"
serde_json = "1"
futures-io = {version="0.3.21",features=["std"]}
futures-core = { version = "0.3.19", default-features = false }
futures-util = {version="0.3.21",features = ["alloc", "sink"]}
chrono = "0.4.19"
rust_decimal = "1.25.0"
byteorder = "1.4.3"
log="0.4"
bigdecimal = { version = "0.2.0", features = ["serde"] }
tokio = {version="1",features=["fs", "net", "rt", "rt-multi-thread", "time", "io-util"]}
tokio-util = {version="0.7.1",features=["compat"]}
